### ISSUE TITLE
Hass.io Dashboard not accessible anymore after deploying a sonospollytts node

### ISSUE THREAD

**Issue by danzeisen** [Supergiovane/node-red-contrib-sonospollytts#28]
Hi

I am trying to use the node-red-contrib-sonospollytts v. 1.1.3 with hass.io. Everything works fine until I reboot hass.io. After reboot, the hass.io dashboard (at :8123) is not reachable anymore. The backend of hass.io and node-red add-on keeps working fine, as the flows work flawlessly.

I tried several ports in the sonospollytts node. I am using the IP of hass.io in sonospollytts. Seems like the webserver started by sonospollytts is conflicting with the hass.io Webserver?

Thanks and BR
Marc

**Comment by Supergiovane** [comment]
Hello Marc,
first of all, thank you for using sonospollytts.
Sonospollytts creates a webserver on port set in the config node.
If you've set a port other than 8123, it shouldn't create any problem.
Are you able to post the node-red log, or at least the hass.io log?

**Comment by danzeisen** [comment]
Hello Giovane (hope that is your name :-) )

If you let me know path and log file name(s) you need, I will upload it here.

**Comment by Supergiovane** [comment]
Hello Marc
my name's Massimo. "Supergiovane" means "superyoung", because i ever feel young :-)
I have no clue in hass.io, so i cannot point you to the correct filename.
If you uninstall sonospollytts, the problems goes away?

**Comment by danzeisen** [comment]
Hi Massimo

It is already enough to remove the sonospollytts node from the flow. I guess the Webserver is only started if a sonospollytts node is present in a flow?

**Comment by Supergiovane** [comment]
Yes, you're correct.
Anyway, i'm installing homeassistant on my qnap nas. If you can wait, i'll test it directly here at home.

**Comment by danzeisen** [comment]
Sure. Take your time! - It is not urgent, although I am very much looking forward to use sonospollytts - it is a very cool node you created! (y)

Let me know if I can help somehow.

**Comment by Supergiovane** [comment]
Thank you. 
I'll ditch into the homeassistant for now, trying to understand how it works.
I'll call you if needed.

**Comment by Supergiovane** [comment]
Thank you for the paypal donation!

**Comment by Supergiovane** [comment]
I've installed Hass.io, nodered and sonospollytts and i cannot replicate your issue, because my system works well, even after a reboot.
![Home_Assistant](https://user-images.githubusercontent.com/37666636/70337184-dcd7d400-184a-11ea-9214-446884da427d.png)

Can you post here your flow (your nodes)? I need to view at least the screenshot of your node-red flow, where sonospollytts is. Thanks

**Comment by danzeisen** [comment]
You won't believe. But now it also works on my installation... I will do a few reboots and continue working on the flow as I did when it failed.
When it failed I could not open the Web GUI of hassio anymore, so I could also not check the system log on the Web GUI. I just could restore a snapshot via the ssh console.

**Comment by Supergiovane** [comment]
Hello Marc
for now is good, but please if you encounter other issues, please let me know.
I've tried several things, including wrong sonospollytts configs, conflicting port and so on.
If i set the same port as hass.io 8123, the sonospollytts node logs that the port is already in use, but hass.io still work, because sonospollytts doesn't even start it's own webserver.
For now, i close the issue but if it happens again, please let me know. Maybe there's something else involved.

Thanks.

**Comment by danzeisen** [comment]
Hi Massimo

I feel like an idiot now - bothered you to try to reproduce the issue I had - and now I can't reproduce it myself... Anyway, I am happy that I can you the sonospollytts now! And if it shows up again, I will first collect the required steps to reproduce it reliably before bothering you. :-)

Thx and BR
Marc

**Comment by Supergiovane** [comment]
There’s no bother! Don’t worry. 
I’ve installed hass.io for the first time, thank to you!
Buon Natale!

**Comment by danzeisen** [comment]
:-)

Anche buon Natale
